import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { AppbarClient } from "../components/AppbarClient";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <div className="min-w-screen min-h-screen bg-slate-700 text-black">
            <AppbarClient />
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
